add "ทำอะไรอยู่ ?"
narze/dumb-questions-th pull request #56
Opened 2022-10-15 14:50 UTC by topten1222

2022-10-15 15:26 UTC, Leomotors requested changes
ซ้ำกับบรรทัดที่ 10 ครับ

2022-10-16 01:01 UTC, topten1222 commented
> 



> ซ้ำกับบรรทัดที่ 10 ครับ
แก้แล้วครับ

2022-10-16 04:05 UTC, tinarskii approved these changes

2022-10-16 08:51 UTC, ronnapatp approved these changes

2022-10-16 13:14 UTC, Leomotors approved these changes

2022-10-16 13:14 UTC, merged